# Generated by Django 3.2.3 on 2021-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, verbose_name='User id')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=256, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Last name')),
                ('language_code', models.CharField(blank=True, max_length=256, verbose_name='Language code')),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='Is blocked bot')),
            ],
            options={
                'verbose_name': 'Chat user',
                'verbose_name_plural': 'Chat users',
            },
        ),
    ]
